newrelic/newrelic-prometheus-configurator

- .github/workflows/push_pr.yaml
- CHANGELOG.md
- Dockerfile
- Makefile
- THIRD_PARTY_NOTICES.md
- assets/licence/THIRD_PARTY_NOTICES.md.tmpl
- assets/licence/overrides
- assets/licence/rules.json
- Adds third party notice.
- Adds a CI check to test if is up to date.
> add third party notice

- charts/newrelic-prometheus/CHANGELOG.md
- charts/newrelic-prometheus/Chart.yaml
- go.mod
- go.sum
- Release v0.0.1 of chart
- Bumps to latest v37 of Prometheus
> chart release

- CHANGELOG.md
- internal/configurator/testdata/endpoints-test.expected.yaml
- internal/configurator/testdata/external-labels-test.expected.yaml
- internal/configurator/testdata/filter-test.expected.yaml
- internal/configurator/testdata/kubernetes-scrape-fields-test.expected.yaml
- internal/configurator/testdata/pods-test.expected.yaml
- internal/configurator/testdata/remote-write-test.expected.yaml
- internal/configurator/testdata/sharding-test.expected.yaml
- internal/configurator/testdata/skip-sharding-test.expected.yaml
- internal/configurator/testdata/static-targets-test.expected.yaml
- internal/remotewrite/config.go
- internal/remotewrite/config_test.go
- internal/remotewrite/remote_write_url.go
- internal/remotewrite/remote_write_url_test.go
Adds collector_name parameter to the RW endpoint URL to identify the source of metrics.
> Add collector_name RW parameter (NR-54665)

- Makefile
- README.md
Executes tooling using go run on the latest version
> use go run for make tooling

- .github/workflows/push_pr.yaml
- .github/workflows/releaseConfigurator.yaml
- .github/workflows/releaseMain.yaml
- .github/workflows/releaseManual.yaml
- .github/workflows/releaseNightly.yaml
- Fix secret availability on reusable workflow
- Removes the deprecated `set-output`
> fix release workflows (NR-52426)

- charts/newrelic-prometheus-agent/CHANGELOG.md
Creating a new release for the chart starting from the release toolkit.
> feat(ci/cd): first changelog based release

- .github/workflows/releaseChart.yaml
- .github/workflows/releaseConfigurator.yaml
Leveraging the new bot https://github.com/newrelic-coreint-team to commit to main.
The secrets is still at repo level for testing purposes, we will need to update it with an org one
> feat(ci/cd): leveraging bot to push changes to main

- .github/renovate.json5
- charts/newrelic-prometheus-agent/Chart.yaml
Adds regex manager to automatically bump configurator version with renovate
> add renovate regex

- .github/rt-dictionary.yaml
- Makefile
Adds the dictionary entry to map the changelog of configurator version bumps
> add configurator tag changlog to dictionary

- charts/newrelic-prometheus-agent/CHANGELOG.md
- charts/newrelic-prometheus-agent/templates/statefulset.yaml
- charts/newrelic-prometheus-agent/tests/configurator_image_test.yaml
`imagePullPolicy ` was not templated correclty. Added a fix and tests
> fix(chart): imagePullPolicy was ignored

- CHANGELOG.md
Signed-off-by: paologallinaharbur <paologallina1992@gmail.com>
> Stable release of configurator

- charts/newrelic-prometheus-agent/CHANGELOG.md
- charts/newrelic-prometheus-agent/Chart.yaml
> Stable release chart

- charts/newrelic-prometheus-agent/Chart.yaml
Please include a summary of the change in your pr and what it's fixing. 
Please delete options that are not relevant.
Please describe the new tests that were added (if applicable).
> Bump configurator version

- charts/newrelic-prometheus-agent/Chart.yaml
Reverts newrelic/newrelic-prometheus-configurator#256
> Revert "Bump configurator version"

- .github/workflows/push_pr.yaml
- CHANGELOG.md
Fix K8s Version Format
For example, "1.24.17" -> "v1.24.17"
> Fix K8s Version Format

- .github/PULL_REQUEST_TEMPLATE.md
Update pull request template in `.github` folder
Please delete options that are not relevant.
Please describe the new tests that were added (if applicable).
> chore: Fix pull request template

- Makefile
Add compile command - it's needed by the reusable release-integration workflow
> fix: Add compile command

- .github/workflows/release-integration.yml
Pass another input with value of the image name in Chart.yaml file which is `configuratorVersion`.
> fix: Pass another input in release-integration.yml

- .github/workflows/security.yaml
Use the reusable security workflow to follow the pattern that our other agents use.
> chore: Use reusable security workflow

- .github/workflows/push_pr.yaml
- CHANGELOG.md
> chore: Remove 1.23 support

- .github/workflows/push_pr.yaml
- CHANGELOG.md
> chore: Add k8s v1.28.0-rc.1 support

- .github/workflows/push_pr.yaml
Disabling [semgrep action that has been deprecated](https://github.com/returntocorp/semgrep-action)
> fix: Disable semgrep action that has been deprecated

- .github/workflows/push_pr.yaml
- CHANGELOG.md
Add full k8s v1.28 support
Update minikube to latest version (note: renovate didn't auto bump the minikube version)
> chore: Update minikube and k8s version

- .github/workflows/push_pr.yaml
- CHANGELOG.md
- Makefile
> ci: add Codecov

- CHANGELOG.md
- README.md
> chore: add codecov badge.

- .github/workflows/_push_image.yaml
- .github/workflows/release-integration.yml
> chore: Update secrets

- CHANGELOG.md
- charts/newrelic-prometheus-agent/templates/statefulset.yaml
> Add security context for init container

- .github/workflows/push_pr.yaml
- CHANGELOG.md
> Add 1.29 and 1.30 support

- .github/workflows/push_pr.yaml
- CHANGELOG.md
Upgrade supported k8s version to v1.32.0 and drop v1.27.0
> feat: Upgrade supported k8s version to v1.32.0 and drop v1.27.0
