.github/dependabot.yml
.github/renovate.json5
.github/workflows/nightlyAndMainImage.yaml
.github/workflows/push_pr.yaml
.github/workflows/releaseIntegration.yaml
test/openmetrics-fake-exporter/Dockerfile

- Adds dependabot for go dependencies
- Adds renovate for chart dependencies
- Avoid mock exporter docker file version bumping

add bots configuration

---

.github/workflows/push_pr.yaml

The label `ci/skip_e2e` mechanism is not working on bots PR since the labels are added after the PR gets created, making bot PRs fail to execute e2e tests.
This PR adds a condition to check  that the secrets exists to run e2e test job.

prevent e2e to run with no secrets

---

.github/cr.yaml
.github/ct.yaml
.github/workflows/push_pr.yaml
.github/workflows/releaseChart.yaml
.gitignore
Makefile
README.md

Merging this PR we will have a new process to release the chart:
- changelog is updated automatically with release notes ([that should be part of the package](https://github.com/helm/chart-releaser/pull/217))
- version is bumped automatically according to the changelog
As soon as well feel comfortable (even now if we want), we can automatize this easily by adding the `schedule` clause in the triggers.
The pipeline has been tested [here](https://github.com/paologallinaharbur/newrelic-prometheus-configurator/pull/1), few releases were created already in the fork from the changelog and dependabot.
My only concern with the approach is if it was easier so install `rt` and run the make, instead of having the logic twice being unable to test the code locally

[NR-55782] Release chart with release toolkit

---

Makefile
charts/newrelic-prometheus-agent/CHANGELOG.md
charts/newrelic-prometheus-agent/Chart.yaml

The \d exists in less instances than [[:digit:]] (available in grep -P but not in POSIX).

fix(promVersion): the version check did not fail

---

.github/workflows/releaseChart.yaml
.github/workflows/releaseConfigurator.yaml

```
$ NEXT= rt next-version
v0.2.1
$ NEXT=v0.0.1 rt next-version
v0.0.1
```
For the integration there is already the "ReleaseManual" action, however, that is not leveraging the release toolkit and breaks the flow
Signed-off-by: paologallinaharbur <paologallina1992@gmail.com>

feat(version): use the release toolkit overwriting the version

---

.github/workflows/push_pr.yaml
CHANGELOG.md
internal/configurator/builder.go
internal/configurator/builder_test.go
internal/remotewrite/config.go
internal/remotewrite/remote_write_url.go
internal/remotewrite/remote_write_url_test.go

This PR sends the Chart version as a `collector_version` query param in the request to the Remote Write Endpoint.
I will add the `NR_PROM_CHART_VERSION` env var in the statefulset init container in a following PR where I'll be releasing the Chart with the new binary of the configurator.

NR-70225: Send collector_version to the RW endpoint

---

.github/workflows/push_pr.yaml
charts/newrelic-prometheus-agent/CHANGELOG.md
charts/newrelic-prometheus-agent/Chart.yaml
charts/newrelic-prometheus-agent/templates/statefulset.yaml

This PR adds the`NR_PROM_CHART_VERSION` env var in the configurator statefulset Chart for to make it available to the configurator to send it to the RW endpoint.
I attach below a screenshot with the `Collector.Version` sent.

NR-70225: set NR_PROM_CHART_VERSION env var in the statefulset init container

---

charts/newrelic-prometheus-agent/values.yaml

Customers migrating from POMI may have dashboards and alerts built using the previous attribute names (e.g. clusterName, namespaceName, etc).  I've added a metric_relabel_config (commented out by default) that can be used to add these legacy attributes to Prometheus metrics for continuity.

feat: Add metric_relabel_config to assist with POMI migrations

---

.github/workflows/releaseChart.yaml
.github/workflows/releaseConfigurator.yaml

There was an error in the pipeline:
```
${{ env.GITHUB_REF_NAME }} != "main"
```
is not working as expected since GITHUB_REF_NAME is a default environment variable and cannot be accessed by `env.` and it is available in the shell only.
That is why the error was:
```
Run if [  != "main" ] || [  != "branch" ];then
/home/runner/work/_temp/f1a9d61a-[7](https://github.com/newrelic/newrelic-prometheus-configurator/actions/runs/4017170116/jobs/6901172427#step:8:8)7d5-4ec3-[8](https://github.com/newrelic/newrelic-prometheus-configurator/actions/runs/4017170116/jobs/6901172427#step:8:9)a03-e49968586243.sh: line 1: [: !=: unary operator expected
/home/runner/work/_temp/f1a9d61a-77d5-4ec3-8a03-e49968586243.sh: line 1: [: !=: unary operator expected
```
Moreover, the pipeline makes generic the …

fix(cicd): default branch check

---

examples/kubernetes/README.md
examples/kubernetes/newrelic-bundle-values.yaml

Adds documentation and sample configuration for the use case where someone has the newrelic/nri-bundle chart and wants to configure the `newrelic-prometheus-configurator` subchart for the Kubelet dashboard.

Kubernetes bundle chart values

---

.github/workflows/push_pr.yaml
charts/newrelic-prometheus-agent/Chart.yaml
charts/newrelic-prometheus-agent/tests/configmap_test.yaml
charts/newrelic-prometheus-agent/tests/integration_filters_test.yaml
charts/newrelic-prometheus-agent/tests/lowdatamode_configmap_test.yaml

Fixes https://github.com/newrelic/newrelic-prometheus-configurator/actions/runs/4866013780/jobs/8677044897?pr=213
Now that https://github.com/helm-unittest/helm-unittest/pull/114 has made Helm3 support the default, we no longer need to specify Helm3.
- Bump helm chart version so that the `Run helm unit tests` github workflow step runs
- Fix helm unit tests so that they pass
- Revert chart version bump

Fix helm unittest

---

charts/newrelic-prometheus-agent/README.md
charts/newrelic-prometheus-agent/README.md.gotmpl

#Description
The original referred doc does not exist anymore.
#Code Changes
Remove the non-existing doc reference from the chart readme.

Remove the broken link in chart README

---

.github/workflows/push_pr.yaml

Modifying push pr workflow to match workflow from [nri-kubernetes](https://github.com/newrelic/nri-kubernetes/blob/main/.github/workflows/push_pr.yaml#L124)

Fix golangci-lint

---

CONTRIBUTING.md

In order to use the release toolkit, we need to follow a certain changelog format: https://github.com/newrelic/release-toolkit/blob/main/generate-yaml/README.md
This PR only updates the PR docs because the changelog is already in the correct format: https://github.com/newrelic/newrelic-prometheus-configurator/blob/main/CHANGELOG.md

chore: Update CHANGELOG format

---

.github/renovate.json5
.github/workflows/changelog.yml
CONTRIBUTING.md

Adding a changelog action that valids if a PR updates a changelog by using the newrelic/release-toolkit/validate-markdown@v1.
- Added changelog
- Added dependencies label to renovatebot
- Update docs
Please delete options that are not relevant.
Please describe the new tests that were added (if applicable).
Not applicable for this pr

chore: Add CHANGELOG github workflow

---

.github/workflows/push_pr.yaml
CHANGELOG.md

The K8s versions in E2e Tests are old.
Check the GitHub workflows that run for PR pushes and:
Remove any references to Kubernetes versions 1.22 or older
Add to tests Kubernetes versions: 1.23.17, 1.24.17, 1.25.13, 1.26.8, 1.27.5
`LATEST_K8S_VERSION: '1.25.13'` is the latest k8s version that does not break the [Run Tests](https://github.com/newrelic/newrelic-prometheus-configurator/blob/705dec67fd83b7d604f0421f8288d2d68aa117fc/.github/workflows/push_pr.yaml#L128)

Update K8s Versions in E2E Tests

---

.github/workflows/push_pr.yaml

Updating minikube version so Helm chart linting works for Kubernetes v 1.27
Please delete options that are not relevant.
Please describe the new tests that were added (if applicable).

ci: Update minikube version

---

.github/workflows/_push_image.yaml

We now keep track of security vulnerabilities in the Security Tab. In addition, failing a PR does not solve the fact that we have to wait for third parties to fix a vulnerabilty, so blocking a PR does not speed up this dependency fix.

fix: Workflow should not fail if Trivy detects vulnerability

---

charts/newrelic-prometheus-agent/CHANGELOG.md
charts/newrelic-prometheus-agent/templates/statefulset.yaml
charts/newrelic-prometheus-agent/tests/configurator_image_test.yaml

feat: add linux node selector.

---

.github/workflows/push_pr.yaml
CHANGELOG.md
charts/internal/test-resources/templates/avalanche.yaml
test/integration/integration_kubernetes_test.go

Test Kube 1.31 and drop 1.26
For `test/integration/integration_kubernetes_test.go`, I edited `Test_EndpointsPhaseDropRule` to expect the Succeeded pod in the dropped target labels.  Historically (before #324 and Kube 1.27.0), that was expected.  Apparently between Kube 1.27 and 1.30 inclusive, that was not expected.  Since PR #324 didn't explain why the change had to be made, I switched it back.
Pin avalanche (used by e2e testing) to a version to avoid the random breaking changes which happened in main.

feat: Add Kube 1.31 support and drop 1.26
